spring.application.name=systemvigiasus

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoramento_epidemiologico
spring.datasource.username=postgres
spring.datasource.password=another02

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect